use std::collections::HashSet;
use std::sync::Arc;

use super::dtos::{BiasScanRequest, BiasScanResult};
use super::model::{BiasCategory, BiasLevel};

#[derive(Clone)]
pub struct BiasDetectionService {
    default_threshold: f32,
    mistral_service: Option<Arc<dyn crate::modules::mistral_ai::client::MistralClient>>,
}

#[derive(Clone, Debug)]
struct BiasRule {
    category: BiasCategory,
    terms: &'static [&'static str],
    weight: f32,
    hint: &'static str,
}

const RULES: &[BiasRule] = &[
    // Gender bias - comprehensive patterns
    BiasRule {
        category: BiasCategory::Gender,
        terms: &[
            // Biological determinism
            "biologically programmed",
            "biologically determined",
            "biologically incapable",
            "biologically inferior",
            "biologically suited",
            "biologically wired",
            "born to be bad",
            "naturally incapable",
            "genetically inferior",
            "hardwired to",
            "wired to be",
            "inherently bad at",
            "inherently worse",
            "innately inferior",
            // Ability stereotypes - women
            "women are bad at",
            "women are bad",
            "women are terrible at",
            "women are terrible",
            "women are worse",
            "women are inferior",
            "women can't",
            "women cannot",
            "women aren't good",
            "women aren't capable",
            "women are incapable",
            "women are unable",
            "women lack the ability",
            "women don't have the",
            "women are generally bad",
            "women are naturally bad",
            "girls are bad",
            "girls are worse",
            "girls can't",
            "girls aren't",
            "females can't",
            "females are bad",
            "females are worse",
            "females are inferior",
            // Ability stereotypes - men
            "men can't",
            "men are bad at",
            "men are incapable of",
            "men don't understand",
            "men lack empathy",
            "men are emotionally",
            // Driving stereotypes
            "bad drivers",
            "terrible drivers",
            "can't drive",
            "cannot drive",
            "shouldn't drive",
            "shouldn't be driving",
            "learn to drive",
            "female driver",
            "woman driver",
            "women drivers",
            "lady driver",
            "asian driver",
            "old driver",
            "drives like a woman",
            "drives like a girl",
            "driving while female",
            // Intelligence stereotypes
            "not smart enough",
            "not intelligent enough",
            "too stupid",
            "too dumb",
            "lack intelligence",
            "lower iq",
            "smaller brain",
            // Superiority/inferiority claims
            "men are naturally better",
            "men are inherently better",
            "men are objectively better",
            "men are superior",
            "man is superior",
            "male superiority",
            "males are superior",
            "men are better",
            "man is better",
            "males are better",
            "boys are better",
            "men are smarter",
            "man is smarter",
            "males are smarter",
            "men are more intelligent",
            "men are stronger",
            "men are more capable",
            "men are more logical",
            "men are more rational",
            "women are weaker",
            "women are less capable",
            "women are more emotional",
            "women are too emotional",
            "women are irrational",
            "women are illogical",
            "women are hysterical",
            "hysterical women",
            "hysterical woman",
            "emotional woman",
            "emotional women",
            // Role stereotypes
            "women belong in",
            "women should stay",
            "woman's place",
            "women's place",
            "women shouldn't work",
            "women shouldn't be",
            "not for women",
            "not meant for women",
            "men make better",
            "why men are better",
            "explain why men",
            "men make better leaders",
            "men make better engineers",
            "men make better scientists",
            "men make better programmers",
            "men make better doctors",
            "men make better bosses",
            "women should be",
            "women should stick to",
            "a woman's job",
            "woman's work",
            "women's work",
            "man's job",
            "man's work",
            "men's work",
            // Career stereotypes
            "not a job for women",
            "not a woman's job",
            "too technical for women",
            "too difficult for women",
            "too hard for women",
            "too complex for women",
            "diversity hire",
            "dei hire",
            "affirmative action hire",
            "quota hire",
            "token woman",
            "token female",
            "token hire",
            "hired because she's a woman",
            "hired because of gender",
            "only hired because",
            // Appearance/behavior
            "dress like a lady",
            "act like a lady",
            "unladylike",
            "not feminine enough",
            "too masculine",
            "man up",
            "be a man",
            "like a girl",
            "throw like a girl",
            "run like a girl",
            "fight like a girl",
            "cry like a girl",
            "sissy",
            "tomboy",
            "butch",
        ],
        weight: 0.35,
        hint: "Avoid gender generalizations and attribute behavior to individuals.",
    },
    // Race/Ethnicity bias - comprehensive
    BiasRule {
        category: BiasCategory::RaceEthnicity,
        terms: &[
            // General stereotyping patterns
            "those people",
            "these people",
            "you people",
            "your people",
            "their kind",
            "that kind of people",
            "people like them",
            "people like you",
            "all of them are",
            "they all",
            "they're all",
            // Immigration
            "all immigrants",
            "immigrants are",
            "immigrants always",
            "immigrants never",
            "illegal alien",
            "illegal aliens",
            "illegals",
            "anchor baby",
            "anchor babies",
            "invasion",
            "invaders",
            "taking our jobs",
            "stealing jobs",
            "go back to",
            "go back where",
            "go home",
            "not from here",
            "don't belong here",
            "doesn't belong",
            "send them back",
            "deport them",
            // Racial superiority/inferiority
            "racially inferior",
            "racially superior",
            "racial superiority",
            "racial inferiority",
            "master race",
            "pure blood",
            "pure race",
            "racial purity",
            "mongrel",
            "mixed breed",
            "half breed",
            "subhuman",
            "untermensch",
            // Group generalizations
            "foreigners are",
            "foreigners always",
            "minorities are",
            "minorities always",
            "black people are",
            "black people always",
            "blacks are",
            "white people are",
            "whites are",
            "asian people are",
            "asians are",
            "latinos are",
            "latinas are",
            "hispanics are",
            "arabs are",
            "jews are",
            "jewish people are",
            "muslims are",
            "chinese are",
            "chinese people are",
            "japanese are",
            "koreans are",
            "mexicans are",
            "indians are",
            "africans are",
            "native americans are",
            "indigenous people are",
            // Slurs and derogatory terms
            "ghetto",
            "hood",
            "thug",
            "thugs",
            "gangster",
            "gangsta",
            "welfare",
            "food stamps",
            "primitive",
            "uncivilized",
            "savage",
            "savages",
            "barbaric",
            "backwards",
            "third world",
            "shithole",
            "exotic",
            "oriental",
            // Coded language
            "urban",
            "inner city",
            "sketchy neighborhood",
            "bad neighborhood",
            "dangerous area",
            "no-go zone",
            "ethnic food",
            "ethnic neighborhood",
            "diverse area",
        ],
        weight: 0.45,
        hint: "Avoid race/ethnicity stereotypes and use evidence-based wording.",
    },
    // Age bias - comprehensive
    BiasRule {
        category: BiasCategory::Age,
        terms: &[
            // Too old/young patterns
            "too old to",
            "too old for",
            "too old",
            "too young to",
            "too young for",
            "too young",
            "at your age",
            "at that age",
            "at his age",
            "at her age",
            "for your age",
            "for their age",
            // Elderly stereotypes
            "elderly cannot",
            "elderly can't",
            "elderly are",
            "elderly people are",
            "old people are",
            "old people can't",
            "old people cannot",
            "old people don't",
            "old folks",
            "old farts",
            "old timers",
            "old timer",
            "old geezer",
            "old codger",
            "senile",
            "dementia",
            "losing their mind",
            "over the hill",
            "past their prime",
            "washed up",
            "outdated",
            "out of touch",
            "dinosaur",
            "fossil",
            "ancient",
            "decrepit",
            "feeble",
            // Youth stereotypes
            "young people are",
            "young people don't",
            "young people can't",
            "kids these days",
            "kids today",
            "youth today",
            "young generation",
            "younger generation",
            "young and naive",
            "young and stupid",
            "young and dumb",
            "inexperienced youth",
            "immature",
            "childish",
            "juvenile",
            "wet behind the ears",
            "green",
            "rookie",
            "newbie",
            // Generation stereotypes
            "millennials are",
            "millennials always",
            "millennials never",
            "boomers are",
            "boomers always",
            "boomers never",
            "gen x are",
            "gen z are",
            "zoomers are",
            "okay boomer",
            "ok boomer",
            "snowflake",
            "snowflakes",
            "entitled generation",
            "lazy generation",
            "participation trophy",
            // Workplace ageism
            "not a cultural fit",
            "overqualified",
            "digital native",
            "tech savvy",
            "learn new technology",
            "adapt to change",
            "fresh perspective",
            "new blood",
            "young blood",
            "energetic team",
            "dynamic environment",
        ],
        weight: 0.30,
        hint: "Reframe age assumptions as role-specific skill criteria.",
    },
    // Religion bias - comprehensive
    BiasRule {
        category: BiasCategory::Religion,
        terms: &[
            // Group generalizations
            "all muslims",
            "muslims are",
            "muslims always",
            "muslim people",
            "islamic people are",
            "all christians",
            "christians are",
            "christians always",
            "christian people",
            "all catholics",
            "catholics are",
            "all jews",
            "jews are",
            "jews always",
            "jewish people are",
            "all hindus",
            "hindus are",
            "hindu people are",
            "all buddhists",
            "buddhists are",
            "all sikhs",
            "sikhs are",
            "all atheists",
            "atheists are",
            "atheists have no",
            "all agnostics",
            "religion makes people",
            "religious people are",
            "religious people always",
            "believers are",
            "non-believers are",
            // Derogatory terms
            "infidel",
            "infidels",
            "kafir",
            "heathen",
            "heathens",
            "pagan",
            "pagans",
            "godless",
            "sinner",
            "sinners",
            "heretic",
            "heretics",
            "apostate",
            "blasphemer",
            // Stereotypes and slurs
            "bible thumper",
            "bible basher",
            "bible beater",
            "holy roller",
            "jesus freak",
            "religious nut",
            "religious fanatic",
            "religious extremist",
            "fundamentalist",
            "zealot",
            "zealots",
            "cult member",
            "cultist",
            "brainwashed",
            "indoctrinated",
            "superstitious",
            // Specific stereotypes
            "terrorist religion",
            "religion of peace",
            "backwards religion",
            "primitive religion",
            "false religion",
            "fake religion",
            "evil religion",
            "violent religion",
            "oppressive religion",
            // Anti-religious
            "sky daddy",
            "imaginary friend",
            "fairy tale",
            "magic man",
            "invisible friend",
            "flying spaghetti",
            "bronze age",
            "mythology",
            "delusion",
            "mental illness",
        ],
        weight: 0.40,
        hint: "Use respectful, non-generalizing language about faith groups.",
    },
    // Disability bias - comprehensive
    BiasRule {
        category: BiasCategory::Disability,
        terms: &[
            // Capability assumptions
            "disabled people cannot",
            "disabled people can't",
            "disabled people are",
            "disabled people don't",
            "disabled people won't",
            "disabled people shouldn't",
            "disabled are",
            "the disabled",
            "handicapped people",
            "handicapped are",
            "crippled",
            "cripple",
            "cripples",
            "invalid",
            "invalids",
            // Physical disability
            "wheelchair bound",
            "wheelchair-bound",
            "confined to wheelchair",
            "stuck in wheelchair",
            "in a wheelchair",
            "lame",
            "gimp",
            "gimpy",
            "midget",
            "dwarf",
            "deformed",
            "disfigured",
            "birth defect",
            // Sensory disability
            "deaf and dumb",
            "deaf-mute",
            "deaf people can't",
            "deaf people are",
            "blind people can't",
            "blind people are",
            "the blind",
            "the deaf",
            "hearing impaired",
            "visually impaired",
            // Cognitive/developmental
            "retarded",
            "retard",
            "retards",
            "mentally retarded",
            "slow",
            "slow learner",
            "special",
            "special needs",
            "special ed",
            "sped",
            "short bus",
            "riding the short bus",
            "window licker",
            "mongoloid",
            "idiot",
            "imbecile",
            "moron",
            "simpleton",
            // Mental health
            "mentally ill people",
            "mentally ill are",
            "the mentally ill",
            "psycho",
            "psychotic",
            "schizo",
            "bipolar",
            "manic",
            "depressive",
            "lunatic",
            "lunatics",
            "maniac",
            "maniacs",
            "crazy",
            "crazy people",
            "insane",
            "insane people",
            "mental",
            "mental case",
            "mental patient",
            "nutcase",
            "nutjob",
            "nut job",
            "loony",
            "looney",
            "loony bin",
            "madman",
            "madwoman",
            "psychopath",
            "sociopath",
            // Autism stereotypes
            "autistic people are",
            "autistics are",
            "autist",
            "on the spectrum",
            "sperg",
            "aspie",
            // Victimhood language
            "suffers from",
            "suffering from",
            "afflicted with",
            "afflicted by",
            "victim of",
            "stricken with",
            "prisoner of",
            "burden",
            "tragic",
            "unfortunate",
            "pitiful",
            "helpless",
            "dependent",
            "incapable",
        ],
        weight: 0.40,
        hint: "Use person-first wording and avoid assumptions about capability.",
    },
    // Socioeconomic bias - comprehensive
    BiasRule {
        category: BiasCategory::SocioEconomic,
        terms: &[
            // Poverty stereotypes
            "poor people are",
            "poor people always",
            "poor people never",
            "poor are",
            "the poor",
            "poor folks",
            "low income people",
            "low income are",
            "lower class",
            "underclass",
            "poverty stricken",
            "impoverished people are",
            "broke people",
            "peasant",
            "peasants",
            // Laziness stereotypes
            "lazy poor",
            "poor and lazy",
            "don't want to work",
            "refuse to work",
            "just get a job",
            "bootstrap",
            "pull themselves up",
            "work harder",
            "handout",
            "handouts",
            "freeloader",
            "freeloaders",
            "moocher",
            "moochers",
            "leech",
            "leeches",
            "parasite",
            "parasites",
            // Welfare stereotypes
            "welfare queen",
            "welfare queens",
            "welfare recipient",
            "welfare recipients",
            "on welfare",
            "living off welfare",
            "government assistance",
            "food stamps",
            "ebt",
            "section 8",
            "public housing",
            "projects",
            "the projects",
            // Class slurs
            "trailer trash",
            "trailer park",
            "white trash",
            "redneck",
            "rednecks",
            "hick",
            "hicks",
            "hillbilly",
            "hillbillies",
            "country bumpkin",
            "bumpkin",
            "yokel",
            "yokels",
            "inbred",
            "cousin lover",
            "backwoods",
            "flyover",
            "flyover country",
            // Homelessness
            "homeless people are",
            "homeless are",
            "the homeless",
            "bum",
            "bums",
            "hobo",
            "hobos",
            "vagrant",
            "vagrants",
            "beggar",
            "beggars",
            "panhandler",
            "panhandlers",
            "transient",
            "drifter",
            "street people",
            "junkie",
            "junkies",
            "druggie",
            "druggies",
            "addict",
            "addicts",
            // Wealth stereotypes
            "rich people are",
            "rich are",
            "the rich",
            "wealthy people are",
            "wealthy are",
            "the wealthy",
            "one percent",
            "one-percenter",
            "fat cat",
            "fat cats",
            "privileged",
            "born rich",
            "trust fund",
            "silver spoon",
            "spoiled rich",
            "entitled rich",
            "greedy rich",
            "snob",
            "snobs",
            "elitist",
            "elitists",
            "bougie",
            "bourgeois",
            "champagne socialist",
            "limousine liberal",
            // Education stereotypes
            "uneducated people",
            "uneducated are",
            "dropout",
            "dropouts",
            "no education",
            "didn't go to college",
            "college educated",
            "overeducated",
            "educated elite",
            "ivory tower",
            // Working class
            "working class are",
            "blue collar",
            "manual labor",
            "minimum wage",
            "mcjob",
            "dead end job",
            "service worker",
        ],
        weight: 0.35,
        hint: "Avoid socioeconomic stereotyping and reference context factors.",
    },
    // Sexual orientation bias - comprehensive
    BiasRule {
        category: BiasCategory::SexualOrientation,
        terms: &[
            // Group generalizations
            "gay people are",
            "gay people always",
            "gay people never",
            "gays are",
            "the gays",
            "homosexuals are",
            "homosexual people",
            "lesbians are",
            "bisexuals are",
            "bisexual people",
            "pansexuals are",
            "asexuals are",
            "lgbtq are",
            "lgbt people",
            "lgbt community is",
            "queer people are",
            "queer community",
            // Transgender stereotypes
            "trans people are",
            "transgender people are",
            "transsexuals are",
            "trannies",
            "tranny",
            "shemale",
            "she-male",
            "ladyboy",
            "he-she",
            "it",
            "crossdresser",
            "transvestite",
            "drag queen",
            "man in a dress",
            "woman with a penis",
            "chicks with dicks",
            // Slurs
            "faggot",
            "fag",
            "fags",
            "homo",
            "homos",
            "dyke",
            "dykes",
            "lesbo",
            "lesbos",
            "queer",
            "fairy",
            "pansy",
            "sissy",
            "queen",
            "fruit",
            "fruits",
            "fruity",
            "sodomite",
            "pervert",
            "perverts",
            "deviant",
            "deviants",
            // Stereotype phrases
            "that's so gay",
            "so gay",
            "no homo",
            "gay voice",
            "gay lisp",
            "gay walk",
            "acts gay",
            "looks gay",
            "seems gay",
            "gaydar",
            "flaming",
            "butch",
            "femme",
            // Ideological
            "gay agenda",
            "homosexual agenda",
            "lgbtq agenda",
            "trans agenda",
            "transgender ideology",
            "gender ideology",
            "woke agenda",
            "lifestyle choice",
            "chosen lifestyle",
            "sexual preference",
            "alternative lifestyle",
            // Religious/moral
            "unnatural",
            "against nature",
            "abomination",
            "sin",
            "sinful",
            "immoral",
            "disgusting",
            "adam and eve",
            "god made",
            "god intended",
            "traditional values",
            "family values",
            "natural order",
            // Grooming accusations
            "groomer",
            "groomers",
            "grooming",
            "pedophile",
            "pedophiles",
            "recruiting",
            "converting",
            "indoctrinating",
            "corrupting",
            "targeting children",
            "think of the children",
            // Gender identity
            "gender confused",
            "confused about gender",
            "gender confusion",
            "mental illness",
            "mentally ill",
            "real man",
            "real woman",
            "real male",
            "real female",
            "biological male",
            "biological female",
            "biologically male",
            "biologically female",
            "born a man",
            "born a woman",
            "actually a man",
            "actually a woman",
            "identifies as",
            "attack helicopter",
            "made up gender",
            "fake gender",
            "two genders",
            "only two genders",
            "chromosomes",
            "xx",
            "xy",
            // Bathroom/sports
            "bathroom bill",
            "men in women's",
            "women's spaces",
            "women's sports",
            "unfair advantage",
            "competing against women",
        ],
        weight: 0.40,
        hint: "Avoid stereotypes about sexual orientation or gender identity.",
    },
    // Nationality bias - comprehensive
    BiasRule {
        category: BiasCategory::Nationality,
        terms: &[
            // General patterns
            "all americans",
            "americans are",
            "americans always",
            "typical american",
            "stupid american",
            "ugly american",
            "all british",
            "british are",
            "british always",
            "typical british",
            "all french",
            "french are",
            "french always",
            "typical french",
            "all germans",
            "germans are",
            "germans always",
            "typical german",
            "all russians",
            "russians are",
            "russians always",
            "typical russian",
            "all chinese",
            "chinese are",
            "chinese always",
            "typical chinese",
            "all japanese",
            "japanese are",
            "japanese always",
            "typical japanese",
            "all koreans",
            "koreans are",
            "koreans always",
            "all indians",
            "indians are",
            "indians always",
            "all mexicans",
            "mexicans are",
            "mexicans always",
            "typical mexican",
            "all brazilians",
            "brazilians are",
            "all australians",
            "australians are",
            "all canadians",
            "canadians are",
            "all irish",
            "irish are",
            "all italians",
            "italians are",
            "all polish",
            "polish are",
            "all swedish",
            "swedish are",
            // Foreigner stereotypes
            "those foreigners",
            "all foreigners",
            "foreigners are",
            "foreigners always",
            "foreign people",
            "foreign workers",
            "outsiders",
            "outsiders are",
            "not from here",
            "not one of us",
            "not like us",
            "their culture",
            "their customs",
            "their way of life",
            "expats are",
            "immigrants from",
            "people from",
            // Stereotypical traits
            "lazy mexican",
            "drunk irish",
            "rude french",
            "cold german",
            "loud american",
            "cheap",
            "stingy",
            "arrogant",
            "rude",
            "dirty",
            "smelly",
            "criminal",
            "violent",
            "terrorists",
            "backwards",
            "uncivilized",
            // Derogatory terms
            "gringo",
            "yankee",
            "yank",
            "limey",
            "kraut",
            "frog",
            "wop",
            "dago",
            "polack",
            "russki",
            "jap",
            "nip",
            "gook",
            "chink",
            "paki",
            "curry muncher",
            "bogan",
            "seppo",
        ],
        weight: 0.30,
        hint: "Avoid generalizations based on nationality or origin.",
    },
    // Harmful language
    BiasRule {
        category: BiasCategory::HarmfulLanguage,
        terms: &[
            "asshole",
            "fuck you",
            "fuck off",
            "fucking",
            "shit",
            "bitch",
            "whore",
            "slut",
            "cunt",
            "dick",
            "pussy",
            "nigger",
            "nigga",
            "faggot",
            "fag",
            "dyke",
            "tranny",
            "retard",
            "spic",
            "chink",
            "gook",
            "wetback",
            "kike",
            "kill yourself",
            "kys",
            "go die",
            "suicide",
            "rape",
            "pedo",
            "pedophile",
            "child porn",
            "cp",
        ],
        weight: 0.50,
        hint: "Avoid offensive, harmful, or dangerous language.",
    },
];

impl BiasDetectionService {
    pub fn new(default_threshold: f32) -> Self {
        Self {
            default_threshold,
            mistral_service: None,
        }
    }

    pub fn new_with_mistral(
        default_threshold: f32,
        mistral_service: Arc<dyn crate::modules::mistral_ai::client::MistralClient>,
    ) -> Self {
        Self {
            default_threshold,
            mistral_service: Some(mistral_service),
        }
    }

    async fn translate_if_needed(&self, text: &str) -> String {
        let Some(mistral_service) = &self.mistral_service else {
            return text.to_owned();
        };

        // First detect language - only translate if NOT English
        let Ok(lang_detection) = mistral_service
            .detect_language(crate::modules::mistral_ai::dtos::LanguageDetectionRequest {
                text: text.to_owned(),
            })
            .await
        else {
            return text.to_owned();
        };

        // Skip translation if already English (to avoid paraphrasing)
        if lang_detection.language.to_lowercase() == "english" {
            return text.to_owned();
        }

        // Translate non-English text to English
        let Ok(translation) = mistral_service
            .translate_text(crate::modules::mistral_ai::dtos::TranslationRequest {
                text: text.to_owned(),
                target_language: "English".to_owned(),
            })
            .await
        else {
            return text.to_owned();
        };

        translation.translated_text
    }

    pub async fn scan(&self, request: BiasScanRequest) -> BiasScanResult {
        let text_to_analyze = self.translate_if_needed(&request.text).await;
        let threshold = normalize_threshold(request.threshold, self.default_threshold);
        let normalized = text_to_analyze.to_ascii_lowercase();

        let mut score = 0.0f32;
        let mut categories = HashSet::new();
        let mut matched_terms = Vec::new();
        let mut mitigation_hints = HashSet::new();

        for rule in RULES {
            for term in rule.terms {
                if normalized.contains(term) {
                    score += rule.weight;
                    categories.insert(rule.category.clone());
                    matched_terms.push((*term).to_owned());
                    mitigation_hints.insert(rule.hint.to_owned());
                }
            }
        }

        score = score.min(1.0);
        let high_cutoff = high_risk_cutoff(threshold);
        let level = if score >= high_cutoff {
            BiasLevel::High
        } else if score >= threshold {
            BiasLevel::Medium
        } else {
            BiasLevel::Low
        };

        let mut categories = categories.into_iter().collect::<Vec<_>>();
        categories.sort_by_key(|category| format!("{category:?}"));

        let mut mitigation_hints = mitigation_hints.into_iter().collect::<Vec<_>>();
        mitigation_hints.sort();

        BiasScanResult {
            score,
            level,
            categories,
            matched_terms,
            mitigation_hints,
        }
    }
}

/// Applies an optional caller override and clamps the effective threshold
/// into a safe range so scoring stays predictable across inputs.
fn normalize_threshold(override_threshold: Option<f32>, default_threshold: f32) -> f32 {
    let threshold = override_threshold
        .filter(|value| value.is_finite())
        .unwrap_or(default_threshold);
    threshold.clamp(0.0, 1.0)
}

/// Derives a stricter "high risk" cutoff from the base threshold while
/// preserving monotonic ordering (`high >= threshold`).
fn high_risk_cutoff(threshold: f32) -> f32 {
    let mut cutoff = (threshold + 0.30).clamp(0.60, 0.95);
    if cutoff < threshold {
        cutoff = threshold;
    }
    cutoff
}

impl Default for BiasDetectionService {
    fn default() -> Self {
        Self {
            default_threshold: 0.35,
            mistral_service: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn returns_low_for_neutral_text() {
        let service = BiasDetectionService::default();
        let result = service
            .scan(BiasScanRequest {
                text: "Summarize the quarterly financial report".to_owned(),
                threshold: None,
            })
            .await;
        assert_eq!(result.level, BiasLevel::Low);
    }

    #[tokio::test]
    async fn returns_high_for_multiple_categories() {
        let service = BiasDetectionService::default();
        let result = service
            .scan(BiasScanRequest {
                text: "Women are bad at math and poor people are lazy".to_owned(),
                threshold: None,
            })
            .await;
        assert_eq!(result.level, BiasLevel::High);
        assert!(result.score > 0.5);
    }

    #[tokio::test]
    async fn nan_threshold_falls_back_to_default_threshold() {
        let service = BiasDetectionService::default();
        let default_result = service
            .scan(BiasScanRequest {
                text: "Women are bad at math".to_owned(),
                threshold: None,
            })
            .await;
        let nan_result = service
            .scan(BiasScanRequest {
                text: "Women are bad at math".to_owned(),
                threshold: Some(f32::NAN),
            })
            .await;
        assert_eq!(default_result.level, nan_result.level);
    }
}
